name: 'Revisor AI Code Review'
description: 'AI-powered PR review using Gemini'
author: 'kitoha'

inputs:
  gemini-api-key:
    description: 'Gemini API Key'
    required: true
  github-token:
    description: 'GitHub Token'
    required: true
    default: ${{ github.token }}

runs:
  using: 'node20'
  main: 'dist/index.js'